#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
if [[ $(hostname) == 'Newton' ]]; then
    bspc wm -O HDMI-0 DVI-D-0
    bspc monitor HDMI-0 -d I II III IV 
    bspc monitor DVI-D-0 -d V VI VII VIII IX X
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width            2
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         false

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true


bspc rule -a Zathura state=tiled
bspc rule -a discord desktop=^9
bspc rule -a Pavucontrol state=floating

/home/max/.scripts/launch-polybar
